version: "3"

services:
  webserver:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.haki.conf:/etc/nginx/conf.d/haki.conf

  app:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    # platform: linux/x86_64 //For arm platform
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_mysql:/var/lib/mysql/

